server:
  port: 9000

logging:
  level:
    root: info

#logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

#jsp setting
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://localhost:3306/practice
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver

#MyBatis setting
mybatis:
  #sql file location
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.spring.mvcproject.database.mybatis
  configuration:
    map-underscore-to-camel-case: true


#database setting -> 민감한 정보가 들어갈 수 있으므로 주의해야함
#springdatasource.url=jdbc:mariadb://localhost:3306/practice
#spring.datasource.username=root
#spring.datasource.password=mariadb
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


